version: '3'

networks:
  polaris_network:

services:
  nginx:
    image: nginx:stable-alpine
    container_name: polaris-nginx
    ports:
      - "8086:80"
    volumes:
      - ./src:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
      - mysql
    networks:
      - polaris_network
    environment:
      - NGINX_HOST=localhost  

  mysql:
    image: mysql:8.0.23
    container_name: polaris-mysql
    restart: unless-stopped
    tty: true
    ports:
      - "7306:3306"
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: "test_pass"
      MYSQL_DATABASE: "polaris_db"
      MYSQL_USER: "test_user"
      MYSQL_PASSWORD: "test_pass"
    volumes:
      - ./db/mysql_data:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password    
    networks:
      - polaris_network
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:4.7
    depends_on:
      - mysql
    ports:
      - "8087:80"
    environment:
      - PMA_HOST=mysql
      - PMA_PORT=3306
    volumes:
      - /sessions
    container_name: polaris-phpmyadmin    
    networks:
      - polaris_network
  php:
    build:
      context: ./php
      dockerfile: Dockerfile
    container_name: polaris-php
    volumes:
      - ./src:/var/www/html
    ports:
      - "9000:9000"
    networks:
      - polaris_network        
  composer:
    image: composer:latest
    container_name: polaris-composer
    volumes:
      - ./src:/var/www/html
    working_dir: /var/www/html
    depends_on:
      - php
    networks:
      - polaris_network
  artisan:
    build:
      context: ./php
      dockerfile: Dockerfile
    container_name: polaris-artisan
    volumes:
      - ./src:/var/www/html
    depends_on:
      - mysql
    working_dir: /var/www/html
    entrypoint: ['/var/www/html/artisan']
    networks:
      - polaris_network
           